"""
Part 2: Maintenance Technician + Wildlife/Remote Site Critical Tasks
"""
import json, os

data = []

# === MAINTENANCE: PERMIT-REQUIRED WORK ===
data.append({"Area":"Plant-Wide","Task":"Lockout/Tagout (LOTO) - Energy Isolation for Maintenance","Role":"Maintenance Tech","Phase":"Normal Ops","Hazards":"Unexpected energization (electrical, hydraulic, pneumatic, thermal, chemical); Stored/residual energy release; Cryogenic inventory behind isolation; Incomplete isolation","Consequence":"Electrocution; Crush/amputation; Cryogenic burn from trapped LNG; Fatality","Pre-Risk":"Critical","Controls":"Site LOTO procedure (multi-lock/tag); Zero-energy verification before work; Isolation register with independent verification; Shift handover protocol for active LOTO; P&ID walkdown to confirm all energy sources","Competency":"LOTO certification; Energy source identification; P&ID reading; Isolation philosophy (positive isolation vs valve)","Training":"LOTO certification course; Practical: Hands-on isolation exercises; Annual recertification; OJT: Supervised isolations (min 10)","Residual":"Medium","Reg Ref":"WorkSafeBC OHS Reg Part 10; CSA Z460"})

data.append({"Area":"Plant-Wide","Task":"Confined Space Entry (Vessels, Columns, Tanks)","Role":"Maintenance Tech","Phase":"Shutdown/Turnaround","Hazards":"Oxygen deficiency/enrichment; Flammable atmosphere; Toxic residues (H2S, mercury, amine); Engulfment; Limited egress; Rescue fatalities (>50% of CS deaths are rescuers)","Consequence":"Asphyxiation; Explosion; Poisoning; Entrapment; Multiple fatalities during failed rescue","Pre-Risk":"Critical","Controls":"Confined space entry permit; Pre-entry atmospheric testing (O2, LEL, toxics) within 20 min of entry; Continuous atmospheric monitoring; Dedicated standby person; Rescue plan with trained rescue team and equipment staged; Mechanical ventilation; Entry/exit log","Competency":"Confined space entry certification; 4-gas monitor operation/calibration; Rescue equipment operation (tripod, winch, SCBA); Atmospheric hazard recognition","Training":"Confined space entry/rescue certification (annual); Practical: 4-gas monitor use + rescue drill; Tabletop: Rescue planning scenarios; First aid certification","Residual":"High","Reg Ref":"WorkSafeBC OHS Reg Part 9; CSA Z1006"})

data.append({"Area":"Plant-Wide","Task":"Hot Work in Hazardous Areas (Welding, Cutting, Grinding)","Role":"Maintenance Tech","Phase":"Normal Ops / Turnaround","Hazards":"Ignition of flammable atmosphere; Fire from sparks/slag; Toxic fume inhalation (welding fumes, zinc, chromium); UV/IR radiation burns; Oxygen enrichment near oxy-fuel equipment","Consequence":"Fire/explosion; Respiratory illness; Eye damage (arc flash); Burns","Pre-Risk":"Critical","Controls":"Hot work permit with gas testing (LEL <1%); Continuous gas monitoring during work; Fire watch during + 30 min post-work; Fire blankets/screens; Welding fume extraction; Flash-back arrestors on oxy-fuel; Area isolation from process","Competency":"Hot work permit process; Gas testing interpretation; Fire watch duties; Welding/cutting certifications (CWB where required)","Training":"Hot work safety course; Fire watch training; Welding certification (trade-specific); Practical: Gas testing + permit completion exercise","Residual":"Medium","Reg Ref":"WorkSafeBC OHS Reg Part 12; NFPA 51B; CSA W117.2"})

data.append({"Area":"Plant-Wide","Task":"Working at Heights (Columns, Vessels, Pipe Racks, Flare Stack)","Role":"Maintenance Tech","Phase":"Normal Ops / Turnaround","Hazards":"Falls from elevation (>3m); Dropped objects; Wind exposure at height; Fatigue/heat stress at height; Rescue from height complications","Consequence":"Fatality from fall; Head injury from dropped object; Suspension trauma post-arrest","Pre-Risk":"Critical","Controls":"100% tie-off >3m; Fall arrest system inspection program; Guardrails where practicable; Tool tethering/barricaded drop zones; Rescue plan for suspended worker (within 15 min); Wind speed limits for work at height; Scaffold inspection/tagging","Competency":"Fall protection certification; Harness inspection; Rescue from heights; Scaffold user awareness","Training":"Fall protection certification (annual); Practical: Harness fitting + rescue exercise; Scaffold user/erector training where required","Residual":"Medium","Reg Ref":"WorkSafeBC OHS Reg Part 11; CSA Z259 series"})

# === MAINTENANCE: EQUIPMENT-SPECIFIC ===
data.append({"Area":"Liquefaction - Cold End","Task":"MR Compressor Maintenance (Overhaul, Seal Replacement, Bearing Change)","Role":"Maintenance Tech","Phase":"Shutdown/Turnaround","Hazards":"Residual refrigerant in casing (flammable); High voltage motor terminals; Heavy lifts (rotor, casing); Confined space inside compressor casing; Cryogenic surfaces","Consequence":"Flash fire from residual gas; Electrocution; Crush injury from heavy lift; Asphyxiation","Pre-Risk":"Critical","Controls":"Full LOTO (electrical + process); Gas-free certification before opening; Crane/rigging plan for heavy lifts; Confined space permit for casing entry; Cryogenic PPE until surfaces warm; Continuous gas monitoring","Competency":"Centrifugal compressor maintenance; Heavy rigging/lifting (certified); High voltage LOTO; Gas-free procedures","Training":"OEM compressor maintenance course; Rigging and lifting certification; LOTO practical; OJT: Supervised overhaul participation","Residual":"Medium","Reg Ref":"WorkSafeBC OHS Reg Parts 10, 15, 19; API 617"})

data.append({"Area":"Liquefaction - Cold End","Task":"Cryogenic Piping/Valve Maintenance (MCHE, Transfer Lines)","Role":"Maintenance Tech","Phase":"Shutdown/Turnaround","Hazards":"Residual cryogenic liquid in piping; Embrittlement of tools/materials; Ice plug formation trapping pressure; Thermal shock during warmup","Consequence":"Cryogenic burn; Pipe/fitting failure from embrittlement; Overpressure from trapped liquid expanding","Pre-Risk":"Critical","Controls":"Drain/depressurize/warm procedures before work; Cryogenic-rated tools and materials verification; No hammering on cold piping; Pressure monitoring during warmup; Cryogenic PPE mandatory; Barricading of work area","Competency":"Cryogenic piping systems; Material compatibility (stainless, nickel alloys); Warmup procedures; Cryogenic PPE use","Training":"Cryogenic safety course; Piping/valve maintenance (trade certification); OJT: Supervised cryo-pipe break","Residual":"Medium","Reg Ref":"WorkSafeBC OHS Reg; ASME B31.3; CSA Z276"})

data.append({"Area":"Gas Pretreatment - Warm End","Task":"Pressure Safety Valve (PSV) Maintenance & Testing","Role":"Maintenance Tech","Phase":"Normal Ops / Turnaround","Hazards":"Uncontrolled pressure release during removal; Exposure to process fluids (H2S, amine, hydrocarbons); Lifting heavy valves at height","Consequence":"High-pressure fluid injection injury; H2S/hydrocarbon exposure; Dropped valve from height","Pre-Risk":"High","Controls":"PSV isolation procedure (car-sealed open bypass where applicable); Depressurization before removal; H2S monitoring during work; Rigging plan for heavy PSVs; Calibration on test bench (not in-situ where possible)","Competency":"PSV maintenance certification; Relief system philosophy; H2S awareness; Rigging basics","Training":"PSV maintenance/testing course (API 510/576 awareness); Practical: PSV removal/reinstallation; Pressure testing procedures","Residual":"Medium","Reg Ref":"WorkSafeBC OHS Reg Part 12; API 510; API 576; ABSA (BC pressure vessel authority)"})

data.append({"Area":"Plant-Wide","Task":"Electrical Maintenance in Hazardous Areas (Ex-rated Equipment)","Role":"Maintenance Tech (Electrical)","Phase":"Normal Ops","Hazards":"Arc flash/blast; Ignition of flammable atmosphere from non-Ex equipment/practices; High voltage contact; Incorrect reinstatement of Ex protection","Consequence":"Electrocution; Arc flash burns (fatal); Explosion from ignition source in classified area; Fire","Pre-Risk":"Critical","Controls":"Hazardous area work permit; Ex-equipment inspection/maintenance per IEC 60079; Arc flash PPE (rated to incident energy); Live work prohibition (de-energize first); Ex-competent person verification before re-energization","Competency":"Hazardous area classification (zones); IEC 60079 Ex-equipment maintenance; Arc flash risk assessment; High voltage switching","Training":"Ex-equipment competency certification (IECEx/CompEx equivalent); Arc flash safety course; High voltage authorization; Annual recertification","Residual":"Medium","Reg Ref":"WorkSafeBC OHS Reg Part 19; CSA C22.1 Section 18; IEC 60079 series"})

data.append({"Area":"Plant-Wide","Task":"Instrument Calibration & Safety System Testing (SIS/ESD/F&G)","Role":"Maintenance Tech (Instrument)","Phase":"Normal Ops","Hazards":"Inadvertent trip of safety system causing unplanned shutdown; Bypassed safety function leaving plant unprotected; Incorrect calibration leading to undetected hazard","Consequence":"Unplanned shutdown (production loss + restart risk); Loss of safety protection layer; Undetected gas release/fire leading to escalation","Pre-Risk":"High","Controls":"SIS impairment procedure (bypass management with time limits); Independent verification of calibration; Proof test procedures per SIL requirements; Bypass register with alarm in control room; Management of Change for any SIS modification","Competency":"SIS/SIL fundamentals; Instrument calibration (pressure, temperature, level, flow, gas); F&G detector testing; Bypass management procedures","Training":"SIS/SIL awareness course; Instrument calibration practical (trade certification); F&G system testing OJT; Bypass management procedure training","Residual":"Medium","Reg Ref":"IEC 61508/61511; CSA Z276; WorkSafeBC OHS Reg"})

# === REMOTE SITE / WILDLIFE ===
data.append({"Area":"Remote Site / General","Task":"Wildlife Encounters - Bear, Cougar, and Other Wildlife Interactions","Role":"All Personnel","Phase":"Normal Ops","Hazards":"Black bear/grizzly bear attack; Cougar attack; Wildlife-vehicle collision on access roads; Wildlife intrusion into work areas; Attractant management failure (food waste)","Consequence":"Serious injury/fatality from animal attack; Vehicle accident; Work interruption; Ecological harm from improper wildlife management","Pre-Risk":"High","Controls":"Wildlife Management & Monitoring Plan (WMMP); Bear-proof waste containers; Food/attractant management policy; Wildlife spotter during outdoor work; Bear spray issued to all field personnel; Wildlife awareness signage; Buffer zones around nesting/denning areas; Report all sightings","Competency":"Wildlife awareness (BC species identification); Bear encounter response; Bear spray use; Attractant management; Reporting procedures","Training":"Bear Aware / Wildlife Awareness course (annual); Bear spray deployment practical; Wildlife encounter response drill; New hire orientation: Wildlife policy","Residual":"Medium","Reg Ref":"BC Wildlife Act; LNG WMMP; WorkSafeBC OHS Reg (general duty)"})

data.append({"Area":"Remote Site / General","Task":"Marine Transport - Personnel Transfer by Vessel (Squamish to Site)","Role":"All Personnel","Phase":"Normal Ops","Hazards":"Man overboard; Vessel collision/grounding in Howe Sound; Cold water immersion (hypothermia in <15 min); Slip/trip during boarding/disembarking; Adverse weather (fog, wind, swells)","Consequence":"Drowning; Hypothermia/death; Traumatic injury; Stranded personnel","Pre-Risk":"High","Controls":"Transport Canada certified vessels; Mandatory PFD/life jacket during transit; Weather go/no-go criteria; Man overboard procedures and equipment; Vessel crew certification; Passenger safety briefing before each departure; Cold water immersion suits available","Competency":"Marine transport safety awareness; PFD use; Man overboard response; Cold water survival basics","Training":"Marine transport safety orientation; Cold water survival awareness; PFD donning drill; Emergency: Man overboard drill (quarterly)","Residual":"Medium","Reg Ref":"Transport Canada Small Vessel Regs; WorkSafeBC; LNG site transportation plan"})

data.append({"Area":"Remote Site / General","Task":"Remote Site Medical Emergency Response","Role":"All Personnel","Phase":"Emergency","Hazards":"Delayed medical evacuation (no road access); Cardiac event/trauma with limited on-site medical capability; Adverse weather preventing helicopter medevac; Multiple casualty incident overwhelming on-site resources","Consequence":"Preventable death from delayed treatment; Deterioration of treatable injury; Mass casualty overwhelm","Pre-Risk":"High","Controls":"On-site paramedic/advanced first aid station; Helicopter medevac agreement (pre-arranged); Marine ambulance transfer capability; Automated External Defibrillator (AED) at multiple locations; Triage protocols for mass casualty; Telemedicine link to hospital; 72-hour emergency supply cache","Competency":"Advanced first aid / OFA Level 3 (BC); AED operation; Triage basics; Emergency communication; Medevac coordination","Training":"OFA Level 3 certification (designated first aid attendants); AED training (all personnel); Mass casualty tabletop (annual); Medevac coordination drill (semi-annual)","Residual":"Medium","Reg Ref":"WorkSafeBC OHS Reg Part 3 (First Aid); BC Ambulance Service; LNG ERP"})

data.append({"Area":"Remote Site / General","Task":"Severe Weather Response (High Wind, Heavy Rain, Lightning, Winter Ice)","Role":"All Personnel","Phase":"Emergency","Hazards":"Lightning strike on tall structures (flare stack, columns); High wind damage to temporary structures/scaffolding; Ice accumulation on walkways/stairs; Reduced visibility from fog/rain; Landslide/debris flow (steep terrain around Howe Sound)","Consequence":"Electrocution from lightning; Structural collapse; Slip/fall injury; Vehicle/vessel accident; Burial from landslide","Pre-Risk":"High","Controls":"Lightning detection system with automated work-stop protocol; Wind speed monitoring with crane/WAH stop limits; Winter maintenance program (sanding, de-icing); Fog go/no-go criteria for marine transport; Geotechnical monitoring of slopes; Severe weather SOP","Competency":"Weather monitoring interpretation; Lightning safety procedures; Winter hazard awareness; Slope stability awareness","Training":"Severe weather response SOP training; Lightning safety awareness; Winter driving/walking hazard awareness; Emergency: Shelter-in-place drill","Residual":"Medium","Reg Ref":"WorkSafeBC OHS Reg; NBC 2020 (wind/snow loads); BC Emergency Program Act"})

# Save
out_dir = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(out_dir, "cri_data_part2.json"), "w") as f:
    json.dump(data, f, indent=2)

print(f"Part 2 complete: {len(data)} records written to cri_data_part2.json")
